### PR TITLE
Moretags Support

### PR DESCRIPTION
**Pull request by gudenau**
This is an incomplete set of changes for More Tags support. I am not sure why a development mixin in More Tags is not working and I am not sure why MoreTags can't be found in one of your blocks.

This is just meant to be a quick PR to try to show how to use More Tags in your mod to resolve the conflicts that it has with More Tags.

Feel free to close this and do a more "proper" implementation on your own.

### CODE REVIEW

**Comment by Lemonszz** [comment]
Nice. I believe the issue is because you added the dependency to the fabric build.gradle rather than the common one.

Unless you've got a forge/common version of MoreTags, I don't think I'd be able to include it without writing a wrapper to support both forge and fabric.

**Comment by gudenau** [comment]
There has to be a way to get it to work, because this is one of those changes that becomes really hard to manage on my side. The other conflicts I resolved things managed to line up in such a way that I could do it from my side, these ones do not seem to be quite as lucky.

**Comment by Lemonszz** [comment]
I'll see what i can do about a quick wrapper, in theory it shouldn't be too hard

**Comment by Lemonszz** [comment]
I've got a potential fix up on in the farmland branch (https://github.com/Lemonszz/Biome-Makeover/tree/farmland)

Only issue is that I can't test the Fabric version because it looks like your RabbitEntity$EatCarrotCropGoal$DevMixin mixin doesn't get remapped (I guess because it's dev only?) and I'm using Mojmap, so it can't find the method and crashes.

`Critical injection failure: @Redirect annotation on isTargetFarmland could not find any targets matching 'isTargetPos' in net.minecraft.world.entity.animal.Rabbit$RaidGardenGoal. Using refmap MoreTags-refmap.json [PREINJECT Applicator Phase -> moretags.mixins.json:farmland.RabbitEntity$EatCarrotCropGoal$DevMixin`.

I'm not all that familiar with mixin plugins so is there anything I can do on my end or you can do on yours to fix it?

**Comment by gudenau** [comment]
I'll go fix that, hopefully the special case isn't needed anymore.

**Comment by gudenau** [comment]
Try out 2.0.3.

**Pull request closed without merging**
